"""Exec Broker — PATH shim enforcement for agent subprocesses.

Intercepts high-risk binaries via PATH shims so that policy.py
rules are enforced even when agents run with --dangerously-skip-permissions.

Usage:
    # Generate shims (run once or on bootstrap)
    from pipeline.exec_broker import ExecBroker
    broker = ExecBroker()
    broker.install_shims()

    # Inject into agent subprocess env
    env = broker.inject_env(base_env)
"""

from __future__ import annotations

import logging
import os
import shutil
import sqlite3
import stat
import sys
import tempfile
import threading
import time
from pathlib import Path

log = logging.getLogger("aifleet.exec_broker")

# Directory where shim scripts live
SHIMS_DIR = Path.home() / ".ai-fleet" / "shims"

# Binaries to intercept — mapped to risk level
# "gate" = needs human approval, "audit" = log only (allow by default)
SHIMMED_BINARIES: dict[str, str] = {
    "git": "audit",  # audit all, policy.py handles gate for push/merge/reset
    "rm": "audit",  # audit all, deny patterns catch rm -rf /
    "brew": "gate",  # installing packages needs approval
    "pip": "gate",  # installing packages needs approval
    "pip3": "gate",
    "npm": "audit",  # audit, gate for publish
    "npx": "audit",
    "ssh": "gate",  # SSH connections need approval
    "scp": "gate",
    "curl": "audit",  # audit, gate for pipe-to-bash
    "launchctl": "gate",  # system services
    "docker": "gate",
    "railway": "gate",
    "kubectl": "gate",
    "terraform": "gate",
}

# Audit log DB path
AUDIT_DB_PATH = Path.home() / ".ai-fleet" / "exec_audit.db"

# Resolve the directory containing policy.py (fleet/pipeline/)
_PIPELINE_DIR = str(Path(__file__).resolve().parent)

# Resolve a trusted Python interpreter at import time (not from shimmed PATH)
_PYTHON = sys.executable or "/usr/bin/python3"

# Lock for thread-safe shim installation
_install_lock = threading.Lock()


def _resolve_real_binary(name: str, shims_dir: Path | None = None) -> str | None:
    """Find the real binary, skipping the shims directory.

    Uses shutil.which(path=...) to avoid mutating os.environ["PATH"].
    """
    skip_dir = str(shims_dir or SHIMS_DIR)
    original_path = os.environ.get("PATH", "")
    clean_dirs = [d for d in original_path.split(os.pathsep) if d != skip_dir]
    clean_path = os.pathsep.join(clean_dirs)

    found = shutil.which(name, path=clean_path)
    if found:
        return found

    # Fallback to common locations
    for prefix in ("/opt/homebrew/bin", "/usr/local/bin", "/usr/bin", "/bin"):
        p = f"{prefix}/{name}"
        if os.path.isfile(p) and os.access(p, os.X_OK):
            return p

    return None


def _init_audit_db() -> sqlite3.Connection:
    """Initialize the audit log database."""
    AUDIT_DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(AUDIT_DB_PATH), timeout=5.0)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("""
        CREATE TABLE IF NOT EXISTS exec_audit (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp INTEGER NOT NULL,
            binary_name TEXT NOT NULL,
            full_command TEXT NOT NULL,
            caller_pid INTEGER,
            parent_pid INTEGER,
            cwd TEXT,
            decision TEXT NOT NULL,
            reason TEXT,
            risk_level TEXT
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS pending_gates (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp INTEGER NOT NULL,
            binary_name TEXT NOT NULL,
            full_command TEXT NOT NULL,
            cwd TEXT,
            status TEXT DEFAULT 'pending',
            reviewed_at INTEGER,
            reviewed_by TEXT
        )
    """)
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_exec_audit_ts ON exec_audit(timestamp DESC)"
    )
    conn.commit()
    return conn


def generate_shim_script(binary_name: str, real_path: str, risk_level: str) -> str:
    """Generate a bash shim script for a binary.

    Security notes:
    - Arguments are passed via sys.argv (heredoc), never interpolated into Python source
    - Policy check failure defaults to deny for gate-level binaries, allow for audit-level
    - No bypass env var — use AIFLEET_SHIMS_BYPASS only from trusted orchestrator
    - Uses absolute Python interpreter path resolved at install time
    """
    fail_default = "gate" if risk_level == "gate" else "allow"
    return f'''#!/bin/bash
# Exec Broker shim for {binary_name}
# Real binary: {real_path}
# Risk level: {risk_level}
# Generated by aifleet exec_broker — do not edit manually

REAL_BINARY="{real_path}"
CALLER_PID=$$
PARENT_PID=$PPID

# Policy check: pass args safely via sys.argv, not string interpolation
DECISION=$("{_PYTHON}" - "{binary_name}" "{risk_level}" "{fail_default}" "$@" <<'POLICY_EOF'
import json, os, sys

binary = sys.argv[1]
risk = sys.argv[2]
fail_default = sys.argv[3]
argv = sys.argv[4:]

# Build command string safely for policy matching
full_cmd = binary + " " + " ".join(argv)

sys.path.insert(0, "{_PIPELINE_DIR}")
try:
    from policy import check_command
    action, reason = check_command(full_cmd)
except Exception as e:
    # Fail closed for gate-level binaries, open for audit-level
    action = fail_default
    reason = f"policy-check-error: {{e}}"

print(f"{{action}}|{{reason}}")
POLICY_EOF
) || DECISION="{fail_default}|policy-runner-crashed"

ACTION=$(echo "$DECISION" | cut -d'|' -f1)
REASON=$(echo "$DECISION" | cut -d'|' -f2-)

# Audit log (fire-and-forget, non-blocking)
"{_PYTHON}" - "{binary_name}" "{risk_level}" "$ACTION" "$REASON" "$CALLER_PID" "$PARENT_PID" "$@" <<'AUDIT_EOF' &
import json, os, sqlite3, sys, time
binary = sys.argv[1]
risk = sys.argv[2]
action = sys.argv[3]
reason = sys.argv[4]
caller_pid = int(sys.argv[5]) if sys.argv[5].isdigit() else 0
parent_pid = int(sys.argv[6]) if sys.argv[6].isdigit() else 0
argv = sys.argv[7:]
full_cmd = binary + " " + " ".join(argv)
try:
    conn = sqlite3.connect("{AUDIT_DB_PATH}", timeout=2)
    conn.execute(
        "INSERT INTO exec_audit (timestamp, binary_name, full_command, caller_pid, parent_pid, cwd, decision, reason, risk_level) VALUES (?,?,?,?,?,?,?,?,?)",
        (int(time.time()), binary, full_cmd, caller_pid, parent_pid, os.getcwd(), action, reason, risk),
    )
    if action == "gate":
        conn.execute(
            "INSERT INTO pending_gates (timestamp, binary_name, full_command, cwd) VALUES (?,?,?,?)",
            (int(time.time()), binary, full_cmd, os.getcwd()),
        )
    conn.commit()
    conn.close()
except Exception:
    pass
AUDIT_EOF

if [ "$ACTION" = "deny" ]; then
    echo "[exec-broker] DENIED: $BINARY_NAME — $REASON" >&2
    exit 126
fi

if [ "$ACTION" = "gate" ]; then
    echo "[exec-broker] GATED: $BINARY_NAME requires human approval — $REASON" >&2
    exit 125
fi

# Allowed — execute the real binary
exec "$REAL_BINARY" "$@"
'''


class ExecBroker:
    """Manages PATH shim enforcement for agent subprocesses."""

    def __init__(self, shims_dir: Path | None = None) -> None:
        self.shims_dir = shims_dir or SHIMS_DIR
        self._real_paths: dict[str, str] = {}

    def install_shims(self) -> dict[str, str]:
        """Generate and install shim scripts. Returns {binary: real_path}.

        Thread-safe via _install_lock. Uses atomic writes (write to temp
        then os.replace) and refuses to overwrite symlinks.
        """
        with _install_lock:
            self.shims_dir.mkdir(parents=True, exist_ok=True)
            # Restrict shims dir to owner only
            self.shims_dir.chmod(stat.S_IRWXU)

            _init_audit_db()

            installed: dict[str, str] = {}

            for binary_name, risk_level in SHIMMED_BINARIES.items():
                real_path = _resolve_real_binary(binary_name, self.shims_dir)
                if not real_path:
                    log.debug("Binary %s not found — skipping shim", binary_name)
                    continue

                shim_path = self.shims_dir / binary_name

                # Refuse to overwrite symlinks (prevent symlink attacks)
                if shim_path.is_symlink():
                    log.warning("Shim %s is a symlink — removing for safety", shim_path)
                    shim_path.unlink()

                # Atomic write: temp file → chmod → os.replace
                script = generate_shim_script(binary_name, real_path, risk_level)
                fd, tmp_path = tempfile.mkstemp(
                    dir=str(self.shims_dir), prefix=f".{binary_name}.", suffix=".tmp"
                )
                try:
                    os.write(fd, script.encode())
                    os.fchmod(fd, stat.S_IRWXU)
                    os.close(fd)
                    os.replace(tmp_path, str(shim_path))
                except Exception:
                    os.close(fd) if not os.get_inheritable(fd) else None
                    if os.path.exists(tmp_path):
                        os.unlink(tmp_path)
                    raise

                self._real_paths[binary_name] = real_path
                installed[binary_name] = real_path
                log.debug(
                    "Installed shim: %s → %s (risk=%s)",
                    binary_name,
                    real_path,
                    risk_level,
                )

            log.info(
                "Exec broker: installed %d shims in %s", len(installed), self.shims_dir
            )
            return installed

    def inject_env(self, base_env: dict[str, str] | None = None) -> dict[str, str]:
        """Return env dict with shims dir prepended to PATH."""
        env = dict(base_env or os.environ)
        current_path = env.get("PATH", "")
        shims_str = str(self.shims_dir)

        if shims_str not in current_path.split(os.pathsep):
            env["PATH"] = shims_str + os.pathsep + current_path

        return env

    def uninstall_shims(self) -> None:
        """Remove all shim scripts."""
        if self.shims_dir.exists():
            for f in self.shims_dir.iterdir():
                if f.is_file() and f.name in SHIMMED_BINARIES:
                    f.unlink()
            log.info("Exec broker: removed shims from %s", self.shims_dir)

    def get_audit_log(self, limit: int = 50) -> list[dict]:
        """Get recent audit log entries."""
        try:
            conn = sqlite3.connect(str(AUDIT_DB_PATH), timeout=2)
            conn.row_factory = sqlite3.Row
            rows = conn.execute(
                "SELECT * FROM exec_audit ORDER BY timestamp DESC LIMIT ?",
                (limit,),
            ).fetchall()
            conn.close()
            return [dict(r) for r in rows]
        except Exception:
            return []

    def get_pending_gates(self) -> list[dict]:
        """Get pending gate requests."""
        try:
            conn = sqlite3.connect(str(AUDIT_DB_PATH), timeout=2)
            conn.row_factory = sqlite3.Row
            rows = conn.execute(
                "SELECT * FROM pending_gates WHERE status = 'pending' ORDER BY timestamp DESC",
            ).fetchall()
            conn.close()
            return [dict(r) for r in rows]
        except Exception:
            return []

    def approve_gate(self, gate_id: int, reviewer: str = "human") -> bool:
        """Approve a pending gate request."""
        try:
            conn = sqlite3.connect(str(AUDIT_DB_PATH), timeout=2)
            conn.execute(
                "UPDATE pending_gates SET status = 'approved', reviewed_at = ?, reviewed_by = ? WHERE id = ?",
                (int(time.time()), reviewer, gate_id),
            )
            conn.commit()
            conn.close()
            return True
        except Exception:
            return False

    def deny_gate(self, gate_id: int, reviewer: str = "human") -> bool:
        """Deny a pending gate request."""
        try:
            conn = sqlite3.connect(str(AUDIT_DB_PATH), timeout=2)
            conn.execute(
                "UPDATE pending_gates SET status = 'denied', reviewed_at = ?, reviewed_by = ? WHERE id = ?",
                (int(time.time()), reviewer, gate_id),
            )
            conn.commit()
            conn.close()
            return True
        except Exception:
            return False

    def status(self) -> dict:
        """Return broker status."""
        shims_installed = []
        if self.shims_dir.exists():
            shims_installed = [
                f.name
                for f in sorted(self.shims_dir.iterdir())
                if f.is_file() and f.name in SHIMMED_BINARIES
            ]

        pending = len(self.get_pending_gates())

        return {
            "shims_dir": str(self.shims_dir),
            "shims_installed": shims_installed,
            "shims_count": len(shims_installed),
            "audit_db": str(AUDIT_DB_PATH),
            "pending_gates": pending,
        }
